apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: first-depl
  name: first-depl
spec:
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: first-depl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: first-depl
    spec:
      containers:
      - image: devopsnthn/byete-hunger
        imagePullPolicy: Always
        name: byete-hunger
        ports:
        - containerPort: 80
