apiVersion: v1
kind: Service
metadata:
  name: byete-service
spec:
  type: LoadBalancer
  selector:
    app: first-depl
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
    